# Generated by Django 3.2.19 on 2023-06-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_articles_publish_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nameEn',
        ),
        migrations.AddField(
            model_name='category',
            name='nameRu',
            field=models.CharField(default='Узбекистан', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='nameUz',
            field=models.CharField(default='Мир', max_length=150),
            preserve_default=False,
        ),
    ]
